worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    upstream users_upstream {
        server users:8081;
    }

    upstream teacolito_upstream {
        server teacolito:8080;
    }

    server {
        listen 80;

        location /users/ {
            proxy_pass http://users_upstream/;
            include proxy_headers.conf;
        }

        location /teacolito/ {
            proxy_pass http://teacolito_upstream/;
            include proxy_headers.conf;
        }
    }
}
